### ISSUE TITLE
"None" daughter-in-law

### ISSUE THREAD

**Issue by SCKaplan** [HCDigitalScholarship/booksofduchesses#100]
I deleted an owner, "Joan of Luxembourg-Ligny," but didn't delete that relationship from Margaret of Flanders, duchess of Burgundy's relatives list in advance, and now I can't access Margaret' Owner page, and that particular relationship is showing up as "None, daugher-in-law" on the website itself.

**Comment by SCKaplan** [comment]
Bumping this, as I still cannot get in to edit Margaret of Flanders

**Comment by fgould** [comment]
Fixed now. Feel free to send me an email if there are urgent issues like this again.
