### ISSUE TITLE
Add Material to Homepage

### ISSUE THREAD

**Issue by sarahwat88** [HCDigitalScholarship/booksofduchesses#102]
Please add the following description to the Homepage. This could be placed in between the project title and our names or below the project title and our names depending on how it looks:

**Books of Duchesses** collects, organizes, and presents data related to late-medieval laywomen and their books. Through an interactive map of Europe, users are able to visualize networks of manuscripts, texts, and readers and explore the libraries and peregrinations of woman book owners. For more information about our methodology and how to use the project see About/Usage. 

Note: Please hyperlink “About/Usage” to relevant page 

Please also add to the Homepage a changing tally of the _women_ owners, books, and texts in the project:

The project currently includes: # Women Owners  # Books   # Texts  

Note: If possible have numbers update automatically as we add new entries

**Comment by fgould** [comment]
Let me know if what is live on the site fits what you would like.

**Comment by sarahwat88** [comment]
Looks great! Thanks!
