### ISSUE TITLE
Addition - Suggest Page 

### ISSUE THREAD

**Issue by sarahwat88** [HCDigitalScholarship/booksofduchesses#105]
Please make the following addition/revision to the Suggest page:

For any feedback or suggestions that can't fit in the form, send us an email at booksofduchesses@gmail.com **or fill out this Google Form to become a Guest Editor.** 

"this Google form" should be hyperlinked with: https://forms.gle/qhQ4HcF7DRDaTHDN6

Thank you!

**Comment by fgould** [comment]
Andy got to this one.
