### ISSUE TITLE
Parent Text 

### ISSUE THREAD

**Issue by sarahwat88** [HCDigitalScholarship/booksofduchesses#113]
We would like to add a Parent Text feature for multi-translation texts

Example: Guillaume de Deguileville's Pilgrimage Trilogy includes three parts which often circulate as separate texts (Le Pèlerinage de la Vie Humaine, Le Pèlerinage de l'Ame and Le Pèlerinage de Jhesucrist) - these subtexts in turn are translated into new versions in different vernaculars such as John Lydgate's English translation of part 2)

Possible solution: add a new field in the text model that says “Parent Text” and allows you to select a text from the text model.

When adding John Lydgate’s _Pilgrimage of the Life of Man_ in the text model you would select Deguileville’s Le Pèlerinage de la Vie Humaine as a parent text

**Comment by SCKaplan** [comment]
Parent-text function exists in the back end but doesn't display on the front end at all

Please add "Parent Text: ******" below "Translator:" on the Text Page
