### ISSUE TITLE
Urgent: Front and back end throwing operational error

### ISSUE THREAD

**Issue by SCKaplan** [HCDigitalScholarship/booksofduchesses#127]
![Screenshot 2021-05-06 16 59 45](https://user-images.githubusercontent.com/17488969/117379593-6440d100-ae9d-11eb-8b15-d69f88b35a20.png)

**Comment by apjanco** [comment]
Rebooted server, working properly now. Let's include a build script for a static site so that we don't have this issue long-term.

**Comment by SCKaplan** [comment]
You rock, thank you!

**Comment by SCKaplan** [comment]
Server needs to be rebooted again :(
