### ISSUE TITLE
Request: Changes to Ownership Information/History

### ISSUE THREAD

**Issue by SCKaplan** [HCDigitalScholarship/booksofduchesses#15]
Please add these additional ownership types:
 - confirmed	documented instance of borrowing
 - confirmed 	patron of printed text
 - confirmed	symbol
 - confirmed	co-ownership
 - confirmed	patron of manuscript
 - possible	co-ownership
 - possible	implied instance of borrowing

Is it possible to indicate multiple ownership types for the same person in the same instance?

**Comment by fgould** [comment]
Im going to make ownership evidence a separate model. That way if you want multiple types you can add a new one that says, for example, "Incription, co-ownership".

**Comment by sarahwat88** [comment]
Making Ownership Evidence a separate model sounds like a great idea. Once that is up and running can we remove the "Conf. or Possible" and "Evidence" fields from the "Date Owned" model since "Ownership type" now covers these?

**Comment by sarahwat88** [comment]
Can we change the drop down box within the "Evidences" model to "Confirmed" and "Possible" rather than "confirmed" and "possibly"?

**Comment by fgould** [comment]
I've added compatibility for multiple ownership types to show up on all pages. I'm going to keep the duplicate field in the admin until I'm sure the change has gone over without a hitch. But for now, there is an example date owned with multiple evidences on Agnes of Burgundy's page, with BnF fr. 92 (which I will change back shortly). Let me know if any changes are needed.
