### ISSUE TITLE
Have searches not be attached to location data

### ISSUE THREAD

**Issue by SCKaplan** [HCDigitalScholarship/booksofduchesses#19]
- If I search for "marie" I get no results, despite having 7 "Marie"s in our owners
 - If I search for "anne" I get 2 results, but we have 5 (6 if you include Jeanne d'Evreux)
 - If I search for "margaret" I get an IndexError: "list index out of range"

**Comment by fgould** [comment]
As of now the search results only show owners who have any sort of geographical info, as we can't effectively filter an owner by dates if they don't have any dates associated with them. I'm adding a more concrete search not attached to the map, but this is a longer project.
