### ISSUE TITLE
Display Order of Owners

### ISSUE THREAD

**Issue by sarahwat88** [HCDigitalScholarship/booksofduchesses#25]
Can Owners be displayed alphabetically rather than in the order added when they pop up as auto fill in various other models? Such as when I am adding an Ownership event to a book? Currently it is hard to find the owner I want quickly. The same goes for other things like tags - can these be displayed alphabetically?

**Comment by fgould** [comment]
I would use the search function when trying to find a specific owner. Just type in the name of the owner and it should come up for most models. If it doesn't then let me know.

**Comment by ikhovryak** [comment]
I added ordering to Owners model and Tags model so now both owners and tags would always display in alphabetical order both on admin page and on the website. If there are places on the website where owners or tags should be kept unordered, please let me know and I will restrict  ordering to an admin page only
