### ISSUE TITLE
Request: Defined size limits for image on Book Owner page

### ISSUE THREAD

**Issue by SCKaplan** [HCDigitalScholarship/booksofduchesses#26]
Please set the height limit on the Owner portrait at around 1/2 the height of the map

**Comment by fgould** [comment]
Set a size limit, but it will crop to keep the alignment. Let me know if there are any weird changes and I can re-evaluate.

**Comment by SCKaplan** [comment]
Images are not resizing, but are being cut off at top and bottom.
