### ISSUE TITLE
Request: Changes to Authors Model, Addition of Printers Model, and Regularization of Translators, Scribes, Illuminators

### ISSUE THREAD

**Issue by sarahwat88** [HCDigitalScholarship/booksofduchesses#28]
**Changes to Authors Model** - Is it possible to move the "Image" and "Geom" options to the bottom of the window and place "Name," "Birth Date," "Death Date," "Gender" and "Link" at the top? This places the highest priority info at the top of the window, facilitating easy entry.  Could we also change "Link" to "Further Information"?

**Addition of Printers Model** - Can we add a Printer Model with the same entry fields in the same order as the Authors Model? So: Name, Birth Date, Death Date, Gender, Further Information, Image, Geom (Location)

Related Change in Book Model - Change the field currently reading "Printer Information" to "Printer" and make possible to select or add from the Printers Model 

**Regularize Translators Model, Scribes Model, Illuminators Model** - Please change these models so that they include the same entry fields in the same order as the Authors Model. So: Name, Birth Date, Death Date, Gender, Further Information, Image, Geom (Location)

Thanks!

**Comment by fgould** [comment]
The link in the author field needs to be a url, do you want a separate field for further information or to have that be the name of the url field?

**Comment by fgould** [comment]
Everything else should be all set

**Comment by sarahwat88** [comment]
Looks great - Thanks! We want the url field to be named "Further Information" - the idea is that the user will click on the link provided to find an author bio provided by an external website.  Does that clear things up?
