### ISSUE TITLE
Request: Dual location/date organization option under Owner Locations on Owner Page

### ISSUE THREAD

**Issue by SCKaplan** [HCDigitalScholarship/booksofduchesses#29]
Currently, list of locations with dates on Owner page seems to be organized by order of entry in Owner model. We would like users to have two options when consulting that data:
1) organized by location (in alphabetical order, I suppose), with the dates listed beside/below in chronological order (could they also have the option to sort ascending or descending according to preference?), e.g.:
   Dijon: 3 January 1424 - 1 February 1424
             12 May 1423 - 4 September 1423
             24 February 1422 - 2 March 1422
2) organized by chronology (again, ideally with the user able to switch between ascending or descending according to their needs), e.g.:
 12 May 1423 - 4 September 1423: Dijon 
 6 September 1423 - 14 September 1423: Auxonne
 14 September 1423 - 19 September 1423: Rouvres-en-Plaine

**Comment by fgould** [comment]
These should already be ordered chronologically, but I can work on reworking the ordering.
