### ISSUE TITLE
Addition - Printer Model

### ISSUE THREAD

**Issue by sarahwat88** [HCDigitalScholarship/booksofduchesses#36]
Addition of Printers Model - Can we add a Printer Model with the same entry fields in the same order as the Authors Model? So: Name, Birth Date, Death Date, Gender, Further Information, Image, Geom (Location)

Thanks!

**Comment by fgould** [comment]
Created. Let me know what you want this to link to.

**Comment by sarahwat88** [comment]
Great, thank you! Can this be linked to the "Printer Information" field in the Book model?

**Comment by fgould** [comment]
Yep. Ready to be filled in now.
