### ISSUE TITLE
Request: Change to Book page

### ISSUE THREAD

**Issue by SCKaplan** [HCDigitalScholarship/booksofduchesses#43]
Display information from About/Content next to Shelfmark

**Comment by SCKaplan** [comment]
Apologies. This was meant to be about Owner pages, not Book pages.

**Comment by fgould** [comment]
Are you sure this is about owner pages? Owners don't have an about/content.

**Comment by SCKaplan** [comment]
Right - but they do have a list of Shelfmarks, which need to have About/Content next to them so that the user isn't required to click through to every individual page to have an idea of the textual contents of an owner's library

**Comment by fgould** [comment]
Added it, open a new issue if modifications are needed.
