### ISSUE TITLE
Request: Add images for Arms and Signature to Owner page, underneath Symbol field

### ISSUE THREAD

**Issue by SCKaplan** [HCDigitalScholarship/booksofduchesses#46]
This was a suggestion by the anonymous reader of our article, and it seems like it would be very helpful for researchers.

**Comment by fgould** [comment]
To clarify, you want an image field in the Owner model called Arms and Signatures, which will appear under symbol on the owner page?

**Comment by SCKaplan** [comment]
I would like two separate image fields, one for Arms and one for Signatures. Signature should definitely go underneath symbol on owner page. Arms can go underneath Signature for the time being, I suppose.

**Comment by fgould** [comment]
Added. Let me know if it needs adjustments.
