### ISSUE TITLE
Request: Modify display dimensions for Arms on owner page

### ISSUE THREAD

**Issue by SCKaplan** [HCDigitalScholarship/booksofduchesses#48]
The display dimensions for the arms are identical to the signature, but this does not work, as it cuts off the majority of the arms.

**Comment by fgould** [comment]
Can you give me some example arms and signatures images to work with so I can get an idea of how to format them?

**Comment by SCKaplan** [comment]
![AgnesArms](https://user-images.githubusercontent.com/17488969/70392311-6ea72480-19a4-11ea-92a2-d4c3e018f0c3.jpg)
![AgnesSig](https://user-images.githubusercontent.com/17488969/70392323-88486c00-19a4-11ea-82dd-5581391b84bc.jpg)
![BnF fr  29sigcrop](https://user-images.githubusercontent.com/17488969/70392442-b8dcd580-19a5-11ea-85e2-3b7faaefb674.jpg)
![BnF fr  926](https://user-images.githubusercontent.com/17488969/70392444-ca25e200-19a5-11ea-9428-476b43578a3a.jpg)

**Comment by fgould** [comment]
Should be fixed. Let me know if you want it adjusted or if its not working properly.
