### ISSUE TITLE
Problem - Search function 

### ISSUE THREAD

**Issue by sarahwat88** [HCDigitalScholarship/booksofduchesses#49]
When I search "Christine de Pizan" using the Author field only one text by her comes up - "Livre de la Cité des Dames." However, in Django she is associated with several other texts including the "Dit de la Pastoure," "Cent Balades d'Amant et de Dame," "Cent balades de Christine de Pizan," the "Le Livre des trois vertus" and the "Epistre Othea." However none of these texts are coming up. Why is this the case? 

Thanks!

**Comment by fgould** [comment]
You've caught a bug. I've fixed this and the tag issue, but it has created another issue with book-text searches. I'll make a separate issue for that and close it when it is fixed.
