### ISSUE TITLE
Create an independent page on the website - About

### ISSUE THREAD

**Issue by sarahwat88** [HCDigitalScholarship/booksofduchesses#54]
Please delete the three paragraphs currently on the homepage and add the following information to an independent “About” page

Would it be possible to have the text below in a page on Django so that Sarah and Kappie can edit it on their own without bothering the tech team each time they want to update it?

_Books of Duchesses_ is a collaborative project run by Dr. S.C. Kaplan (Rice University) and Dr. Sarah Wilma Watson (Haverford College). It collects, organizes, and presents data related to late-medieval laywomen and their books. Through an interactive map of Europe, users are able to visualize networks of manuscripts, texts, and readers and explore the libraries and peregrinations of woman book owners.

The data collected in the project has the potential to shift scholarly paradigms by challenging narratives of national literary history and uncovering the active role played by women in creating, consuming literary and material culture and in circulating texts across national, geographic, and generational borders.

The geographic scope of the project is initially limited to England and French-speaking regions on the continent, including France and Burgundy. The time frame of the project is currently bounded between 1350 and 1550, a period of intense political, interfamilial, and interpersonal changes and exchanges due to the Hundred Years War and its aftermath.

The project is currently in an early stage of development. New data is being added every day and we are working to improve the user interface. If you have suggestions for the project, please contact us at booksofduchesses@gmail.com.

The project is generously supported by the Haverford Digital Scholarship Team, comprising Andy Janco supervising Freddie Gould.

For related publications, see S.C. Kaplan and Sarah Wilma Watson, “_Books of Duchesses: Mapping Women Book Owners in Francophone Europe, 1350-1550_: Initial Findings,” Journal of the Early Book Society 23 (forthcoming 2021).

**Comment by fgould** [comment]
Done. Let me know if the current set up is good.
