### ISSUE TITLE
Create an independent page on the website - How to Use the Project

### ISSUE THREAD

**Issue by sarahwat88** [HCDigitalScholarship/booksofduchesses#55]
Please create an independent page on the website - "How to Use the Project"

Again, if Sarah and Kappie can have the ability to edit this text in Django rather than request an update every time, that would be great.

**How to Use _Books of Duchesses_**

Visitors are greeted by an interactive map of Europe. Purple pins appear on the map to identify locations where women book owners resided or traveled. Clicking on a specific purple pin causes a list of women to appear, accompanied by the dates of their time in that location. Each woman’s name is hyperlinked, allowing the visitor to click through to the owner’s individual page and learn more about the owner and her book collection. 

While purple owner pins appear by default on the map, a user can also choose to display “Books.” Green pins will appear, identifying locations where books owned by women were made, stored, or transported. Clicking on a specific green pin causes a list of books to appear, accompanied by the dates when the books were at those locations. The books are also hyperlinked, allowing the user to click through to the book’s individual page and learn more about the book’s various owners and the texts it contains. Extant books are identified by their current library shelfmark while non-extant books (that is, books which no longer exist or cannot be definitively identified with a manuscript, such as those listed in medieval inventories or wills) are designated as NE 1, NE 2 etc.   

The search bar to the left of the map allows the visitor to adjust the results that appear on the map. User can define a date range and/or search by Owner, Shelfmark, Text, Author, and Tag (Genre or Topic – Example: “Romance” or “Childbirth”). Results related to your search will appear as pins on the map and in list form below the map.

**Comment by fgould** [comment]
Done. You can edit both this and the about page's text under the model "Abouts".
