### ISSUE TITLE
Create an independent page on the website - Suggestions 

### ISSUE THREAD

**Issue by sarahwat88** [HCDigitalScholarship/booksofduchesses#56]
Please create an independent page on the website - "Suggestions" - with the text below. 

Would you like to add data to the project? 

- Request an account here or send us an email at booksofduchesses@gmail.com

Would you like to offer feedback on the project?

- Please send us an email at booksofduchesses@gmail.com

Please link "here" to a place where a use can create a guest account in Django - but **Note:** Guest accounts in Django should have limitations set on them - guests should not be able to alter or delete existing information but only add new information - all guest entries should be flagged and must be approved by Kappie or Sarah before entering the database fully

**Comment by fgould** [comment]
I've got a preliminary form up that is secure. It can be found in the header of the site as well. Going to shelve this for now and get back to spruce it up at another time.
