### ISSUE TITLE
Request: Modify information about books as displayed on Owner page

### ISSUE THREAD

**Issue by SCKaplan** [HCDigitalScholarship/booksofduchesses#63]
The way this information is currently formatted is not particularly user-friendly or as complete as we would like. Ideally, it will look like this:

	Hyperlink to book: Contents from About box on Book model
		Confirmed/Possible ownership DATE RANGE
                      type(s) of ownership evidence

E.g., from Agnes of Burgundy’s page:
	Beinecke MS 204: Somme le roi/Miroir du monde
		Confirmed ownership c. 1460/1470-1476
                        inscription

**Comment by fgould** [comment]
Let me know how it looks now.
