### ISSUE TITLE
Error: Sizing of owner portrait still problematic

### ISSUE THREAD

**Issue by SCKaplan** [HCDigitalScholarship/booksofduchesses#66]
![Screenshot 2020-01-28 10 45 50](https://user-images.githubusercontent.com/17488969/73293963-788e1c80-41ca-11ea-860d-021addf42144.png)

**Comment by fgould** [comment]
Sorry about that! I've made it so pictures keep their original size (don't get cut down) and scale to take up less space. This will create more variance in the height of the image (i.e. pushing down the family tree stuff) but will keep everything consistent.
