### ISSUE TITLE
Errors: Owner page sorting by location

### ISSUE THREAD

**Issue by SCKaplan** [HCDigitalScholarship/booksofduchesses#67]
1) Any use of the Sort button for locations results in the book list contents disappearing

2) Descending/Ascending date still sorting by day number rather than year. If this problem is not easily solved on the back end, let me know and I'll re-enter things in Year Month Day format.

**Comment by fgould** [comment]
First issue is fixed. Sorting should be better now, or at least more standard with the rest of the site and without any issues I've seen.
