### ISSUE TITLE
Paris - only showing one owner

### ISSUE THREAD

**Issue by sarahwat88** [HCDigitalScholarship/booksofduchesses#69]
When I click on the purple Paris pin on the map the only book owner that appears is "Marie of Anjou." A week ago when I clicked on this pin multiple women showed up including Isabel of Bavaria and Alice Chaucer. Why are these women no longer appearing?

**Comment by fgould** [comment]
After much hunting, the error is a tiny difference in the coordinates of the owner locations which caused the map to put a bunch of single pins on top of each other. If this comes up again it may not be that obvious, so be on the lookout for missing/too few entries on the map and I'll make sure it's not too widespread.
