### ISSUE TITLE
Change - Date Owned Model

### ISSUE THREAD

**Issue by sarahwat88** [HCDigitalScholarship/booksofduchesses#70]
There appears to be some redundancy in this model. It asks you to selected "confirmed" or "possible" from a drop down menu and the type of evidence from a drop down menu. This feature seems unnecessary now that we can add this information via the "ownership type" field. The "ownership type" field is also better because it allows us to select two types of ownership evidence. For example, a book might be linked to a female owner because it bears both her coat of arms and her personal inscription.

**Comment by fgould** [comment]
Removed the redundant field
