### ISSUE TITLE
Error: Map pin display

### ISSUE THREAD

**Issue by sarahwat88** [HCDigitalScholarship/booksofduchesses#78]
Owner and Book Pins will not display on the map at the same time. When I attempt to tick both boxes in the side bar I receive the following error message: 

Request Method: | POST
-- | --
https://booksofduchesses.com/
2.2.2
ValueError
time data 'April-January-1' does not match format '%Y-%B-%d'
/usr/lib/python3.5/_strptime.py in _strptime, line 343
/usr/bin/uwsgi-core
3.5.2
['.',  '',  '/srv/booksofduchesses_env/lib/python35.zip',  '/srv/booksofduchesses_env/lib/python3.5',  '/srv/booksofduchesses_env/lib/python3.5/plat-x86_64-linux-gnu',  '/srv/booksofduchesses_env/lib/python3.5/lib-dynload',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/srv/booksofduchesses_env/lib/python3.5/site-packages']
Fri, 17 Apr 2020 15:53:35 +0000

**Comment by fgould** [comment]
Fixed as a result of previous issue.
