### ISSUE TITLE
Error: Map search bar throwing mutiple errors 

### ISSUE THREAD

**Issue by sarahwat88** [HCDigitalScholarship/booksofduchesses#79]
The map search bar is throwing numerous errors. 

An attempt to limit the pins to a particular time frame results in an error message.

A search for a specific owner works.

A search for a specific shelfmark results in an error message.

A search for a specific text results in an error message.

A search for a specific author results in an error message. 

A search for a specific tag results in an error message. 

Interestingly, none of these issues occur if you switch to just green book pins.

**Comment by fgould** [comment]
Issue seems to be fixed now, stemmed from an issue with owner locations. Should something persist please reopen and let me know.
