### ISSUE TITLE
Family Tree Expansion 

### ISSUE THREAD

**Issue by sarahwat88** [HCDigitalScholarship/booksofduchesses#84]
Please add another generation on either side of the family tree: 
Grandparents/ Up two generations  - including "Grandmother" "Grandfather" "Great Aunt" "Great Uncle"
and Grandchildren/ Down two generations - including "Granddaughter" "Grandson" "Grand Niece" "Grand Nephew" 

Thank you!

**Comment by fgould** [comment]
Added, let me know if you encounter issues.

**Comment by SCKaplan** [comment]
Hi Freddie, so when I added Margaret of Bavaria as grandmother to Isabel of Bourbon, countess of Charrolais, Margaret shows up in "Children/Down one generation", and the same is true of Isabel of Bourbon when she was added as Margaret's granddaughter.

**Comment by fgould** [comment]
Fixed.
