### ISSUE TITLE
Simplify Display - Owner Page

### ISSUE THREAD

**Issue by sarahwat88** [HCDigitalScholarship/booksofduchesses#86]
Is it possible to simplify the Owner Page in two places? 

The top header should stay the same. Example - Book Owner: Jacquetta of Luxembourg, duchess of Bedford

But would it be possible to simplify the headers for the woman's locations and library? For example,  "Jacquetta of Luxembourg, duchess of Bedford's Locations" would be simplified to "Jacquetta of Luxembourg's Locations" and "Jacquetta of Luxembourg, duchess of Bedford's library" would become "Jacquetta of Luxembourg's library" 

I assume that right now the code is imputing the full owner name and adding " 's locations " but would it be possible to tweak the code so that ignores everything after the comma? 

Thanks!

**Comment by fgould** [comment]
This is easy enough to implement assuming that with every owner we can delimit their name on the first comma. If that won't create any weird cutoffs I'll move ahead.

**Comment by sarahwat88** [comment]
Yes, I think that should work!

Thank you as always for all of your work on this!

**Comment by fgould** [comment]
Added, let me know if you spot any issues. Happy to help!

**Comment by sarahwat88** [comment]
Hi there! Looks like there is a problem with this recent fix. Some women's names are getting cut off too early.

Example - Ann Stafford de Ver's Library should be Ann Stafford de Ver**e**'s Library - https://booksofduchesses.com/owners/Ann%20Stafford%20de%20Vere/

Example - Emelyn Bremsche's Library should be Emelyn Bremsche**t**'s Library - https://booksofduchesses.com/owners/Emelyn%20Bremschet/

Thanks!

**Comment by fgould** [comment]
Unfortunate typo in the code. Fixed.
