### ISSUE TITLE
URGENT: OperationError at /admin/

### ISSUE THREAD

**Issue by SCKaplan** [HCDigitalScholarship/booksofduchesses#96]
![Screenshot 2020-08-17 13 04 19](https://user-images.githubusercontent.com/17488969/90439333-0401c900-e09b-11ea-9114-8e6afb28cbc9.png)

**Comment by SCKaplan** [comment]
This also means that the website isn't accessible

**Comment by fgould** [comment]
Restarted the server and it seems to be fine now. Sorry about that.
