### ISSUE TITLE
Error: Marie of Cleves owner model

### ISSUE THREAD

**Issue by SCKaplan** [HCDigitalScholarship/booksofduchesses#97]
Other female owners are not throwing this error
![Screenshot 2020-10-09 13 26 53](https://user-images.githubusercontent.com/17488969/95628599-fc7bf200-0a43-11eb-9eca-aa4031d44bc4.png)

**Comment by SCKaplan** [comment]
Possibly an error left after transforming NE 442 into BnF fr. 1430

**Comment by fgould** [comment]
I removed an empty entry, potentially from the transformation you described. I would make sure to check that the transformation data is updated (i.e BnF fr. 1430 is there if it is supposed to be).
