### ISSUE TITLE
Books not showing up on homepage map properly

### ISSUE THREAD

**Issue by SCKaplan** [HCDigitalScholarship/booksofduchesses#99]
When the book box is clicked, no pins show up on the map, even with more specific search terms entered, although they do appear in the list of books underneath the map, and the appropriate pin shows up on the individual book's page.

**Comment by SCKaplan** [comment]
Edit: Books that I have confirmed have locations (eg. BnF fr. 1456) are still not showing up in the list of books with locations belonging to a particular owner. Is this because the owner at the date of the book location differs from the searched for owner? If so, the search parameters need to be adjusted on the back end to include *all* book owners.

**Comment by fgould** [comment]
Fixed, looks like an unintended consequence of some documentation work I did. Leaving this open until it's completely resolved.
